language: python
sudo: required
addons:
  apt:
    packages:
      - chromium-chromedriver
dist: xenial
python:
  - '3.6'
  - '3.7'

matrix:
  fast_finish: true

notifications:
  email: false

install:
  - sudo apt-get -qq update
  - make dev
  - pip install coveralls

before_script:
  - make check
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver

script:
  - travis_wait coverage run --source=streamscrape -m pytest tests

after_success:
  - coveralls
